# fly.toml app configuration file generated for social-content-assistant on 2025-07-30T14:57:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'social-content-assistant'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
